import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export function exportBOQPDF(project, sections) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.width

  // Header
  doc.setFillColor(29, 158, 117)
  doc.rect(0, 0, pageWidth, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('BILL OF QUANTITIES', 14, 12)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`Project: ${project.name}`, 14, 20)
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 14, 20, { align: 'right' })

  let y = 36
  let grandTotal = 0

  sections.forEach(sec => {
    const items = sec.boq_items || []
    const sectionTotal = items.reduce((s, it) => s + (parseFloat(it.quantity) || 0) * (parseFloat(it.rate) || 0), 0)
    grandTotal += sectionTotal

    // Section title
    doc.setFillColor(245, 245, 243)
    doc.rect(14, y - 4, pageWidth - 28, 8, 'F')
    doc.setTextColor(17, 17, 16)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text(sec.title, 16, y + 1)
    doc.text(`$${Math.round(sectionTotal).toLocaleString()}`, pageWidth - 14, y + 1, { align: 'right' })
    y += 8

    // Items table
    autoTable(doc, {
      startY: y,
      head: [['Description', 'Unit', 'Qty', 'Rate ($)', 'Amount ($)', 'Status']],
      body: items.map(it => [
        it.description || '-',
        it.unit || '-',
        it.quantity || 0,
        `$${(parseFloat(it.rate) || 0).toLocaleString()}`,
        `$${Math.round((parseFloat(it.quantity) || 0) * (parseFloat(it.rate) || 0)).toLocaleString()}`,
        it.is_paid ? '✓ Paid' : '✗ Unpaid'
      ]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [24, 95, 165], textColor: 255, fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 60 }, 1: { cellWidth: 15 }, 2: { cellWidth: 15 },
        3: { cellWidth: 25 }, 4: { cellWidth: 25 }, 5: { cellWidth: 25 }
      },
      didParseCell: (data) => {
        if (data.column.index === 5 && data.section === 'body') {
          const isPaid = data.cell.raw === '✓ Paid'
          data.cell.styles.textColor = isPaid ? [15, 110, 86] : [163, 45, 45]
        }
      },
      margin: { left: 14, right: 14 },
    })

    y = doc.lastAutoTable.finalY + 8
  })

  // Summary
  const vatAmt = Math.round(grandTotal * 0.18)
  y += 4
  doc.setDrawColor(200, 200, 200)
  doc.line(14, y, pageWidth - 14, y)
  y += 6
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text('Subtotal:', pageWidth - 60, y)
  doc.text(`$${Math.round(grandTotal).toLocaleString()}`, pageWidth - 14, y, { align: 'right' })
  y += 6
  doc.text('VAT (18%):', pageWidth - 60, y)
  doc.text(`$${vatAmt.toLocaleString()}`, pageWidth - 14, y, { align: 'right' })
  y += 8
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(29, 158, 117)
  doc.text('TOTAL:', pageWidth - 60, y)
  doc.text(`$${Math.round(grandTotal + vatAmt).toLocaleString()}`, pageWidth - 14, y, { align: 'right' })

  // Footer
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by Construction OS', 14, doc.internal.pageSize.height - 8)
  doc.text(`Page 1`, pageWidth - 14, doc.internal.pageSize.height - 8, { align: 'right' })

  doc.save(`BOQ-${project.name}-${new Date().toISOString().slice(0,10)}.pdf`)
}

export function exportSiteReportPDF(project, reports) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.width

  doc.setFillColor(29, 158, 117)
  doc.rect(0, 0, pageWidth, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('SITE REPORTS', 14, 12)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`Project: ${project.name}`, 14, 20)
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 14, 20, { align: 'right' })

  autoTable(doc, {
    startY: 34,
    head: [['Date', 'Weather', 'Workers', 'Work Done', 'Issues']],
    body: reports.map(r => [
      r.report_date,
      r.weather || '-',
      r.workers_present || 0,
      r.work_done || '-',
      r.issues || 'None'
    ]),
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [24, 95, 165], textColor: 255 },
    columnStyles: {
      0: { cellWidth: 22 }, 1: { cellWidth: 20 }, 2: { cellWidth: 18 },
      3: { cellWidth: 80 }, 4: { cellWidth: 50 }
    },
    margin: { left: 14, right: 14 },
  })

  doc.save(`SiteReports-${project.name}-${new Date().toISOString().slice(0,10)}.pdf`)
}

export function exportPayrollPDF(project, members) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.width

  doc.setFillColor(29, 158, 117)
  doc.rect(0, 0, pageWidth, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('PAYROLL REPORT', 14, 12)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`Project: ${project.name}`, 14, 20)
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 14, 20, { align: 'right' })

  const rows = members.map(m => {
    const base = parseFloat(m.base_salary) || 0
    const expected = parseInt(m.expected_days) || 22
    const attended = parseInt(m.attended_days) || 0
    const actual = expected > 0 ? Math.round(base * Math.min(attended / expected, 1)) : base
    const deduction = base - actual
    return [
      m.name,
      m.role || '-',
      `${attended}/${expected}`,
      `${Math.round((attended/expected)*100)}%`,
      `$${Math.round(base).toLocaleString()}`,
      `-$${Math.round(deduction).toLocaleString()}`,
      `$${Math.round(actual).toLocaleString()}`,
      m.pay_status === 'paid' ? '✓ Paid' : '✗ Unpaid'
    ]
  })

  autoTable(doc, {
    startY: 34,
    head: [['Name', 'Role', 'Attendance', '%', 'Base', 'Deduction', 'Actual', 'Status']],
    body: rows,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [24, 95, 165], textColor: 255 },
    margin: { left: 14, right: 14 },
    didParseCell: (data) => {
      if (data.column.index === 7 && data.section === 'body') {
        const isPaid = data.cell.raw === '✓ Paid'
        data.cell.styles.textColor = isPaid ? [15, 110, 86] : [163, 45, 45]
      }
    }
  })

  const totalBase = members.reduce((s, m) => s + (parseFloat(m.base_salary) || 0), 0)
  const totalActual = members.reduce((s, m) => {
    const base = parseFloat(m.base_salary) || 0
    const exp = parseInt(m.expected_days) || 22
    const att = parseInt(m.attended_days) || 0
    return s + (exp > 0 ? Math.round(base * Math.min(att/exp, 1)) : base)
  }, 0)

  let y = doc.lastAutoTable.finalY + 10
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(17, 17, 16)
  doc.text(`Total base payroll: $${Math.round(totalBase).toLocaleString()}`, 14, y)
  y += 6
  doc.setTextColor(163, 45, 45)
  doc.text(`Total deductions: -$${Math.round(totalBase - totalActual).toLocaleString()}`, 14, y)
  y += 6
  doc.setTextColor(15, 110, 86)
  doc.text(`Total actual payroll: $${Math.round(totalActual).toLocaleString()}`, 14, y)

  doc.save(`Payroll-${project.name}-${new Date().toISOString().slice(0,10)}.pdf`)
}